### ISSUE TITLE
Error in filterAndTrim (corresponding output file missing)

### ISSUE THREAD

**Issue by Dwrgi** [jkzorz/SituSeq#1]
I have tried to run Preprocessing.R a few times now and I keep getting the following error message:

Error in filterAndTrim(fnFs, filtFs, trimLeft = trimLeft, trimRight = trimRight,  : 
  Every input file must have a corresponding output file.

Because I had some other problems (not related to SituSeq) running it in RStudio on Windows, I tried running it in R on Ubuntu in a VB. Installing all the prerequisites seemingly worked fine.

I don't quite understand what the problem is?

The fastq files are in subdirectories as described in the instructions, with one fastq file per barcode, e.g. subdirectory barcode09_tbc01 contains the file BC09.fastq

Thanks!

-------------------------------------------------
**Full output:**
> source("Preprocessing.R")

Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,

    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,

    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,

    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,

    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,

    union, unique, unsplit, which.max, which.min

Loading required package: BiocParallel

Loading required package: Biostrings

Loading required package: S4Vectors

Loading required package: stats4

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:base’:

    expand.grid, I, unname

Loading required package: IRanges

Loading required package: XVector

Loading required package: GenomeInfoDb

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading required package: Rsamtools

Loading required package: GenomicRanges

Loading required package: GenomicAlignments

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats

Attaching package: ‘MatrixGenerics’

The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,

    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,

    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,

    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,

    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,

    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,

    colWeightedMeans, colWeightedMedians, colWeightedSds,

    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,

    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,

    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,

    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,

    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,

    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,

    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,

    rowWeightedSds, rowWeightedVars

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with

    'browseVignettes()'. To cite Bioconductor, see

    'citation("Biobase")', and for packages 'citation("pkgname")'.

Attaching package: ‘Biobase’

The following object is masked from ‘package:MatrixGenerics’:

    rowMedians

The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

Loading required package: Rcpp

── Attaching packages ───────────────────────────────────────────────────────────── tidyverse 1.3.2 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4

✔ tibble  3.1.6     ✔ dplyr   1.0.8

✔ tidyr   1.2.0     ✔ stringr 1.4.0

✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ──────────────────────────────────────────────────────────────── tidyverse_conflicts() ──

✖ dplyr::collapse()   masks Biostrings::collapse(), IRanges::collapse()

✖ dplyr::combine()    masks Biobase::combine(), BiocGenerics::combine()

✖ purrr::compact()    masks XVector::compact()

✖ purrr::compose()    masks ShortRead::compose()

✖ dplyr::count()      masks matrixStats::count()

✖ dplyr::desc()       masks IRanges::desc()

✖ tidyr::expand()     masks S4Vectors::expand()

✖ dplyr::filter()     masks stats::filter()

✖ dplyr::first()      masks GenomicAlignments::first(), S4Vectors::first()

✖ dplyr::id()         masks ShortRead::id()

✖ dplyr::lag()        masks stats::lag()

✖ dplyr::last()       masks GenomicAlignments::last()

✖ ggplot2::Position() masks BiocGenerics::Position(), base::Position()

✖ purrr::reduce()     masks GenomicRanges::reduce(), IRanges::reduce()

✖ dplyr::rename()     masks S4Vectors::rename()

✖ dplyr::slice()      masks XVector::slice(), IRanges::slice()

✖ tibble::view()      masks ShortRead::view()

[1] "barcode09_tbc01"

character(0)

[1] "barcode10_tbc02"

character(0)

[1] "barcode11_tbc03"

character(0)

[1] "barcode12_tbc04"

character(0)

[1] "barcode13_tbc05"

character(0)

[1] "barcode14_tbc06"

character(0)

[1] "barcode15_tbc07"

character(0)

[1] "barcode16_tbc08"

character(0)

[1] "barcode17_tbc09"

character(0)

[1] "barcode18_tbc10"

character(0)

[1] "barcode19_tbc11"

character(0)

[1] "barcode20_tbc12"

character(0)

[1] "barcode21_tbc13"

character(0)

[1] "barcode22_tbc14"

character(0)

[1] "barcode23_tbc15"

character(0)

[1] "barcode25_tbc17"

character(0)

[1] "barcode26_tbc18"

character(0)

[1] "barcode27_tbc19"

character(0)

[1] "barcode28_tbc20"

character(0)

[1] "barcode32_ntc"

character(0)

Error in filterAndTrim(fnFs, filtFs, trimLeft = trimLeft, trimRight = trimRight,  : 

  Every input file must have a corresponding output file.

>

**Comment by Dwrgi** [comment]
If it helps anyone else:
I tried gzipping all fastq files to fastq.gz versions in their respective subdirectories and this seems to have solved the problem.

**Comment by jkzorz** [comment]
Hi! Thanks for bringing this to my attention. I've just updated the Preprocessing script so that it can now take zipped or unzipped fastq files as input.
