### ISSUE TITLE
Mapping between SRA files and barcodes

### ISSUE THREAD

**Issue by ryanames-eagle** [jkzorz/SituSeq#3]
Hi,

I'm looking into SituSeq and want to run the data on the examples provided in the paper. I have downloaded the relevant Nanopore files from SRA, which come as SRR{ID}.fastq. However, the scripts want the files and directory structure as the come off the machine i.e. barcode01_sample1 etc. 

Do you have a mapping or suggested file/folder structure to get everything up and running? 

Thanks

**Comment by jkzorz** [comment]
Hey,

Thanks for bringing this up. I've added some practice data (from the paper) with the correct file format to github here: https://github.com/jkzorz/SituSeq/tree/main/data

Also, in the data directory, the file Nanopore_SRA_metadata.csv (https://github.com/jkzorz/SituSeq/blob/main/data/Nanopore_SRA_metadata.csv) now has a suggested key between all 40 SRA  sample accessions (accession column) and barcode/library IDs (ONT_barcode_ID column) that will match with the analysis done in the paper. 

Hope this helps! 
Jackie

**Comment by ryanames-eagle** [comment]
Brilliant - thank you
